/**
* EaselJS
* Visit http://easeljs.com/ for documentation, updates and examples.
*
* Copyright (c) 2011 Grant Skinner
* 
* Permission is hereby granted, free of charge, to any person
* obtaining a copy of this software and associated documentation
* files (the "Software"), to deal in the Software without
* restriction, including without limitation the rights to use,
* copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following
* conditions:
* 
* The above copyright notice and this permission notice shall be
* included in all copies or substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
* OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
* HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
* WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
**/
(function(l){UID=function(){throw"UID cannot be instantiated";};UID._nextID=0;UID.get=function(){return UID._nextID++};l.UID=UID})(window);(function(l){Ticker=function(){throw"Ticker cannot be instantiated.";};Ticker._listeners=[];Ticker._pauseable=[];Ticker._paused=false;Ticker._inited=false;Ticker._startTime=0;Ticker._pausedTime=0;Ticker._ticks=0;Ticker._pausedTickers=0;Ticker._interval=50;Ticker._intervalID=null;Ticker._lastTime=0;Ticker._times=[];Ticker.addListener=function(c,a){if(!Ticker._inited){Ticker._inited=true;Ticker._startTime=Ticker._getTime();Ticker._times.push(0);Ticker.setInterval(Ticker._interval)}this.removeListener(c);
Ticker._pauseable[Ticker._listeners.length]=a==null?true:a;Ticker._listeners.push(c)};Ticker.removeListener=function(c){if(Ticker._listeners!=null){c=Ticker._listeners.indexOf(c);if(c!=-1){Ticker._listeners.splice(c,1);Ticker._pauseable.splice(c,1)}}};Ticker.removeAllListeners=function(){Ticker._listeners=[];Ticker._pauseable=[]};Ticker.setInterval=function(c){Ticker._intervalID!=null&&clearInterval(Ticker._intervalID);Ticker._lastTime=Ticker.getTime(false);Ticker._interval=c;Ticker._intervalID=setInterval(Ticker._tick,
c)};Ticker.getInterval=function(){return Ticker._interval};Ticker.getFPS=function(){return 1E3/Ticker._interval};Ticker.setFPS=function(c){Ticker.setInterval(1E3/c)};Ticker.getMeasuredFPS=function(c){if(Ticker._times.length<2)return-1;if(c==null)c=Ticker.getFPS()>>1;c=Math.min(Ticker._times.length-1,c);return 1E3/((Ticker._times[0]-Ticker._times[c])/c)};Ticker.setPaused=function(c){Ticker._paused=c};Ticker.getPaused=function(){return Ticker._paused};Ticker.getTime=function(c){return Ticker._getTime()-
Ticker._startTime-(c?Ticker._pausedTime:0)};Ticker.getTicks=function(c){return Ticker._ticks-(c?Ticker._pausedTickers:0)};Ticker._tick=function(){Ticker._ticks++;var c=Ticker.getTime(false),a=c-Ticker._lastTime,b=Ticker._paused;if(b){Ticker._pausedTickers++;Ticker._pausedTime+=a}Ticker._lastTime=c;for(var d=Ticker._pauseable,e=Ticker._listeners.slice(),f=e?e.length:0,g=0;g<f;g++){var h=d[g],i=e[g];i==null||b&&h||i.tick==null||i.tick(a)}Ticker._times.unshift(c);Ticker._times.length>100&&Ticker._times.pop()};
Ticker._getTime=function(){return(new Date).getTime()};l.Ticker=Ticker})(window);(function(l){MouseEvent=function(a,b,d){this.initialize(a,b,d)};var c=MouseEvent.prototype;c.stageX=0;c.stageY=0;c.type=null;c.nativeEvent=null;c.onMouseMove=null;c.onMouseUp=null;c.initialize=function(a,b,d){this.type=a;this.stageX=b;this.stageY=d};c.clone=function(){var a=new MouseEvent(this.type,this.stageX,this.stageY);a.nativeEvent=this.nativeEvent;return a};c.toString=function(){return"[MouseEvent (type="+this.type+" stageX="+this.stageX+" stageY="+this.stageY+")]"};l.MouseEvent=MouseEvent})(window);(function(l){Matrix2D=function(a,b,d,e,f,g){this.initialize(a,b,d,e,f,g)};var c=Matrix2D.prototype;Matrix2D.identity=null;Matrix2D.DEG_TO_RAD=Math.PI/180;c.a=1;c.b=0;c.c=0;c.d=1;c.tx=0;c.ty=0;c.alpha=1;c.shadow=null;c.compositeOperation=null;c.initialize=function(a,b,d,e,f,g){if(a!=null)this.a=a;if(b!=null)this.b=b;if(d!=null)this.c=d;if(e!=null)this.d=e;if(f!=null)this.tx=f;if(g!=null)this.ty=g};c.prepend=function(a,b,d,e,f,g){var h=this.tx;if(a!=1||b!=0||d!=0||e!=1){var i=this.a,j=this.c;this.a=
i*a+this.b*d;this.b=i*b+this.b*e;this.c=j*a+this.d*d;this.d=j*b+this.d*e}this.tx=h*a+this.ty*d+f;this.ty=h*b+this.ty*e+g};c.append=function(a,b,d,e,f,g){var h=this.a,i=this.b,j=this.c,k=this.d;this.a=a*h+b*j;this.b=a*i+b*k;this.c=d*h+e*j;this.d=d*i+e*k;this.tx=f*h+g*j+this.tx;this.ty=f*i+g*k+this.ty};c.prependMatrix=function(a){this.prepend(a.a,a.b,a.c,a.d,a.tx,a.ty);this.prependProperties(a.alpha,a.shadow,a.compositeOperation)};c.appendMatrix=function(a){this.append(a.a,a.b,a.c,a.d,a.tx,a.ty);this.appendProperties(a.alpha,
a.shadow,a.compositeOperation)};c.prependTransform=function(a,b,d,e,f,g,h,i,j){if(f%360){var k=f*Matrix2D.DEG_TO_RAD;f=Math.cos(k);k=Math.sin(k)}else{f=1;k=0}if(i||j){this.tx-=i;this.ty-=j}if(g||h){g*=Matrix2D.DEG_TO_RAD;h*=Matrix2D.DEG_TO_RAD;this.prepend(f*d,k*d,-k*e,f*e,0,0);this.prepend(Math.cos(h),Math.sin(h),-Math.sin(g),Math.cos(g),a,b)}else this.prepend(f*d,k*d,-k*e,f*e,a,b)};c.appendTransform=function(a,b,d,e,f,g,h,i,j){if(f%360){var k=f*Matrix2D.DEG_TO_RAD;f=Math.cos(k);k=Math.sin(k)}else{f=
1;k=0}if(g||h){g*=Matrix2D.DEG_TO_RAD;h*=Matrix2D.DEG_TO_RAD;this.append(Math.cos(h),Math.sin(h),-Math.sin(g),Math.cos(g),a,b);this.append(f*d,k*d,-k*e,f*e,0,0)}else this.append(f*d,k*d,-k*e,f*e,a,b);if(i||j){this.tx-=i*this.a+j*this.c;this.ty-=i*this.b+j*this.d}};c.rotate=function(a){var b=Math.cos(a);a=Math.sin(a);var d=this.a,e=this.c,f=this.tx;this.a=d*b-this.b*a;this.b=d*a+this.b*b;this.c=e*b-this.d*a;this.d=e*a+this.d*b;this.tx=f*b-this.ty*a;this.ty=f*a+this.ty*b};c.skew=function(a,b){a*=Matrix2D.DEG_TO_RAD;
b*=Matrix2D.DEG_TO_RAD;this.append(Math.cos(b),Math.sin(b),-Math.sin(a),Math.cos(a),0,0)};c.scale=function(a,b){this.a*=a;this.d*=b;this.tx*=a;this.ty*=b};c.translate=function(a,b){this.tx+=a;this.ty+=b};c.identity=function(){this.alpha=this.a=this.d=1;this.b=this.c=this.tx=this.ty=0;this.shadow=this.compositeOperation=null};c.invert=function(){var a=this.a,b=this.b,d=this.c,e=this.d,f=this.tx,g=a*e-b*d;this.a=e/g;this.b=-b/g;this.c=-d/g;this.d=a/g;this.tx=(d*this.ty-e*f)/g;this.ty=-(a*this.ty-b*
f)/g};c.decompose=function(a){if(a==null)a={};a.x=this.tx;a.y=this.ty;a.scaleX=Math.sqrt(this.a*this.a+this.b*this.b);a.scaleY=Math.sqrt(this.c*this.c+this.d*this.d);var b=Math.atan2(-this.c,this.d),d=Math.atan2(this.b,this.a);if(b==d){a.rotation=d/Matrix2D.DEG_TO_RAD;if(this.a<0&&this.d>=0)a.rotation+=a.rotation<=0?180:-180;a.skewX=a.skewY=0}else{a.skewX=b/Matrix2D.DEG_TO_RAD;a.skewY=d/Matrix2D.DEG_TO_RAD}return a};c.appendProperties=function(a,b,d){this.alpha*=a;this.shadow=b||this.shadow;this.compositeOperation=
d||this.compositeOperation};c.prependProperties=function(a,b,d){this.alpha*=a;this.shadow=this.shadow||b;this.compositeOperation=this.compositeOperation||d};c.clone=function(){var a=new Matrix2D(this.a,this.b,this.c,this.d,this.tx,this.ty);a.shadow=this.shadow;a.alpha=this.alpha;a.compositeOperation=this.compositeOperation;return a};c.toString=function(){return"[Matrix2D (a="+this.a+" b="+this.b+" c="+this.c+" d="+this.d+" tx="+this.tx+" ty="+this.ty+")]"};Matrix2D.identity=new Matrix2D(1,0,0,1,0,
0);l.Matrix2D=Matrix2D})(window);(function(l){Point=function(a,b){this.initialize(a,b)};var c=Point.prototype;c.x=0;c.y=0;c.initialize=function(a,b){this.x=a==null?0:a;this.y=b==null?0:b};c.clone=function(){return new Point(this.x,this.y)};c.toString=function(){return"[Point (x="+this.x+" y="+this.y+")]"};l.Point=Point})(window);(function(l){Rectangle=function(a,b,d,e){this.initialize(a,b,d,e)};var c=Rectangle.prototype;c.x=0;c.y=0;c.width=0;c.height=0;c.initialize=function(a,b,d,e){this.x=a==null?0:a;this.y=b==null?0:b;this.width=d==null?0:d;this.height=e==null?0:e};c.clone=function(){return new Rectangle(this.x,this.y,this.width,this.height)};c.toString=function(){return"[Rectangle (x="+this.x+" y="+this.y+" width="+this.width+" height="+this.height+")]"};l.Rectangle=Rectangle})(window);(function(l){Shadow=function(a,b,d,e){this.initialize(a,b,d,e)};var c=Shadow.prototype;Shadow.identity=null;c.color=null;c.offsetX=0;c.offsetY=0;c.blur=0;c.initialize=function(a,b,d,e){this.color=a;this.offsetX=b;this.offsetY=d;this.blur=e};c.toString=function(){return"[Shadow]"};c.clone=function(){return new Shadow(this.color,this.offsetX,this.offsetY,this.blur)};Shadow.identity=new Shadow(null,0,0,0);l.Shadow=Shadow})(window);(function(l){SpriteSheet=function(a,b,d,e){this.initialize(a,b,d,e)};var c=SpriteSheet.prototype;c.image=null;c.frameWidth=0;c.frameHeight=0;c.frameData=null;c.loop=true;c.totalFrames=0;c.initialize=function(a,b,d,e){this.image=a;this.frameWidth=b;this.frameHeight=d;this.frameData=e};c.toString=function(){return"[SpriteSheet]"};c.clone=function(){var a=new SpriteSheet(this.image,this.frameWidth,this.frameHeight,this.frameData);a.loop=this.loop;a.totalFrames=this.totalFrames;return a};l.SpriteSheet=
SpriteSheet})(window);(function(l){function c(b,d){this.f=b;this.params=d}c.prototype.exec=function(b){this.f.apply(b,this.params)};Graphics=function(b){this.initialize(b)};var a=Graphics.prototype;Graphics.getRGB=function(b,d,e,f){if(b!=null&&e==null){f=d;e=b&255;d=b>>8&255;b=b>>16&255}return f==null?"rgb("+b+","+d+","+e+")":"rgba("+b+","+d+","+e+","+f+")"};Graphics.getHSL=function(b,d,e,f){return f==null?"hsl("+b%360+","+d+"%,"+e+"%)":"hsla("+b%360+","+d+"%,"+e+"%,"+f+")"};Graphics.STROKE_CAPS_MAP=["butt","round","square"];
Graphics.STROKE_JOINTS_MAP=["miter","round","bevel"];Graphics._ctx=document.createElement("canvas").getContext("2d");Graphics.beginCmd=new c(Graphics._ctx.beginPath,[]);Graphics.fillCmd=new c(Graphics._ctx.fill,[]);Graphics.strokeCmd=new c(Graphics._ctx.stroke,[]);a._strokeInstructions=null;a._strokeStyleInstructions=null;a._fillInstructions=null;a._instructions=null;a._oldInstructions=null;a._activeInstructions=null;a._active=false;a._dirty=false;a._minX=NaN;a._minY=NaN;a._maxX=NaN;a._maxY=NaN;a._boundsQueue=
null;a._x=0;a._y=0;a.initialize=function(b){this.clear();this._ctx=Graphics._ctx;with(this)eval(b)};a.draw=function(b){this._dirty&&this._updateInstructions();for(var d=this._instructions,e=0,f=d.length;e<f;e++)d[e].exec(b)};a.getBounds=function(){this._boundsQueue.length&&this._updateBounds();return isNaN(this._minX)?null:new Rectangle(this._minX,this._minY,this._maxX-this._minX,this._maxY-this._minY)};a.moveTo=function(b,d){this._activeInstructions.push(new c(this._ctx.moveTo,[b,d]));this._x=b;
this._y=d;return this};a.lineTo=function(b,d){this._dirty=this._active=true;this._activeInstructions.push(new c(this._ctx.lineTo,[b,d]));this._extendBounds(this._x,this._y);this._extendBounds(b,d);this._x=b;this._y=d;return this};a.arcTo=function(b,d,e,f,g){this._dirty=this._active=true;this._activeInstructions.push(new c(this._ctx.arcTo,[b,d,e,f,g]));return this};a.arc=function(b,d,e,f,g,h){this._dirty=this._active=true;if(h==null)h=false;this._activeInstructions.push(new c(this._ctx.arc,[b,d,e,
f,g,h]));return this};a.quadraticCurveTo=function(b,d,e,f){this._dirty=this._active=true;this._activeInstructions.push(new c(this._ctx.quadraticCurveTo,[b,d,e,f]));return this};a.bezierCurveTo=function(b,d,e,f,g,h){this._dirty=this._active=true;this._activeInstructions.push(new c(this._ctx.bezierCurveTo,[b,d,e,f,g,h]));this._boundsQueue.push(new c(this._bezierCurveToBounds,[_x,_y,b,d,e,f,g,h]));return this};a.rect=function(b,d,e,f){this._dirty=this._active=true;this._activeInstructions.push(new c(this._ctx.rect,
[b,d,e-1,f]));this._extendBounds(b,d);this._extendBounds(b+e,d+f);return this};a.closePath=function(){if(this._active){this._dirty=true;this._activeInstructions.push(new c(this._ctx.closePath,[]))}return this};a.clear=function(){this._instructions=[];this._oldInstructions=[];this._activeInstructions=[];this._strokeStyleInstructions=this._strokeInstructions=this._fillInstructions=null;this._active=this._dirty=false;this._boundsQueue=[];this._minX=this._minY=this._maxX=this._maxY=NaN;return this};a.beginFill=
function(b){this._active&&this._newPath();this._fillInstructions=b?[new c(this._setProp,["fillStyle",b])]:null;return this};a.beginLinearGradientFill=function(b,d,e,f,g,h){this._active&&this._newPath();e=this._ctx.createLinearGradient(e,f,g,h);f=0;for(g=b.length;f<g;f++)e.addColorStop(d[f],b[f]);this._fillInstructions=[new c(this._setProp,["fillStyle",e])];return this};a.beginRadialGradientFill=function(b,d,e,f,g,h,i,j){this._active&&this._newPath();e=this._ctx.createRadialGradient(e,f,g,h,i,j);f=
0;for(g=b.length;f<g;f++)e.addColorStop(d[f],b[f]);this._fillInstructions=[new c(this._setProp,["fillStyle",e])];return this};a.beginBitmapFill=function(b,d){this._active&&this._newPath();var e=this._ctx.createPattern(b,d||"");this._fillInstructions=[new c(this._setProp,["fillStyle",e])];return this};a.endFill=function(){this.beginFill(null);return this};a.setStrokeStyle=function(b,d,e,f){this._active&&this._newPath();this._strokeStyleInstructions=[new c(this._setProp,["lineWidth",b==null?"1":b]),
new c(this._setProp,["lineCap",d==null?"butt":isNaN(d)?d:Graphics.STROKE_CAPS_MAP[d]]),new c(this._setProp,["lineJoin",e==null?"miter":isNaN(e)?e:Graphics.STROKE_JOINTS_MAP[e]]),new c(this._setProp,["miterLimit",f==null?"10":f])];return this};a.beginStroke=function(b){this._active&&this._newPath();this._strokeInstructions=b?[new c(this._setProp,["strokeStyle",b])]:null;return this};a.beginLinearGradientStroke=function(b,d,e,f,g,h){this._active&&this._newPath();e=this._ctx.createLinearGradient(e,f,
g,h);f=0;for(g=b.length;f<g;f++)e.addColorStop(d[f],b[f]);this._strokeInstructions=[new c(this._setProp,["strokeStyle",e])];return this};a.beginRadialGradientStroke=function(b,d,e,f,g,h,i,j){this._active&&this._newPath();e=this._ctx.createRadialGradient(e,f,g,h,i,j);f=0;for(g=b.length;f<g;f++)e.addColorStop(d[f],b[f]);this._strokeInstructions=[new c(this._setProp,["strokeStyle",e])];return this};a.beginBitmapStroke=function(b,d){this._active&&this._newPath();var e=this._ctx.createPattern(b,d||"");
this._strokeInstructions=[new c(this._setProp,["strokeStyle",e])];return this};a.endStroke=function(){this.beginStroke(null);return this};a.curveTo=a.quadraticCurveTo;a.drawRect=a.rect;a.drawRoundRect=function(b,d,e,f,g){this.drawRoundRectComplex(b,d,e,f,g,g,g,g);return this};a.drawRoundRectComplex=function(b,d,e,f,g,h,i,j){this._dirty=this._active=true;this._activeInstructions.push(new c(this._ctx.moveTo,[b+g,d]),new c(this._ctx.lineTo,[b+e-h,d]),new c(this._ctx.arc,[b+e-h,d+h,h,-Math.PI/2,0,false]),
new c(this._ctx.lineTo,[b+e,d+f-i]),new c(this._ctx.arc,[b+e-i,d+f-i,i,0,Math.PI/2,false]),new c(this._ctx.lineTo,[b+j,d+f]),new c(this._ctx.arc,[b+j,d+f-j,j,Math.PI/2,Math.PI,false]),new c(this._ctx.lineTo,[b,d+g]),new c(this._ctx.arc,[b+g,d+g,g,Math.PI,Math.PI*3/2,false]));return this};a.drawCircle=function(b,d,e){this.arc(b,d,e,0,Math.PI*2);return this};a.drawEllipse=function(b,d,e,f){this._dirty=this._active=true;var g=e/2*0.5522848,h=f/2*0.5522848,i=b+e,j=d+f;e=b+e/2;f=d+f/2;this._activeInstructions.push(new c(this._ctx.moveTo,
[b,f]),new c(this._ctx.bezierCurveTo,[b,f-h,e-g,d,e,d]),new c(this._ctx.bezierCurveTo,[e+g,d,i,f-h,i,f]),new c(this._ctx.bezierCurveTo,[i,f+h,e+g,j,e,j]),new c(this._ctx.bezierCurveTo,[e-g,j,b,f+h,b,f]));return this};a.drawPolyStar=function(b,d,e,f,g,h){this._dirty=this._active=true;if(g==null)g=0;g=1-g;if(h==null)h=0;else h/=180/Math.PI;var i=Math.PI/f;this._activeInstructions.push(new c(this._ctx.moveTo,[b+Math.cos(h)*e,d+Math.sin(h)*e]));for(var j=0;j<f;j++){h+=i;g!=1&&this._activeInstructions.push(new c(this._ctx.lineTo,
[b+Math.cos(h)*e*g,d+Math.sin(h)*e*g]));h+=i;this._activeInstructions.push(new c(this._ctx.lineTo,[b+Math.cos(h)*e,d+Math.sin(h)*e]))}return this};a.clone=function(){var b=new Graphics;b._instructions=this._instructions.slice();b._activeInstructions=this._activeInstructions.slice();b._oldInstructions=this._oldInstructions.slice();if(this._fillInstructions)b._fillInstructions=this._fillInstructions.slice();if(this._strokeInstructions)b._strokeInstructions=this._strokeInstructions.slice();if(this._strokeStyleInstructions)b._strokeStyleInstructions=
this._strokeStyleInstructions.slice();b._active=this._active;b._dirty=this._dirty;return b};a.toString=function(){return"[Graphics]"};a.mt=a.moveTo;a.lt=a.lineTo;a.at=a.arcTo;a.bt=a.bezierCurveTo;a.qt=a.quadraticCurveTo;a.a=a.arc;a.r=a.rect;a.cp=a.closePath;a.c=a.clear;a.f=a.beginFill;a.lf=a.beginLinearGradientFill;a.rf=a.beginRadialGradientFill;a.bf=a.beginBitmapFill;a.ef=a.endFill;a.ss=a.setStrokeStyle;a.s=a.beginStroke;a.ls=a.beginLinearGradientStroke;a.rs=a.beginRadialGradientStroke;a.bs=a.beginBitmapStroke;
a.es=a.endStroke;a.dr=a.drawRect;a.rr=a.drawRoundRect;a.rc=a.drawRoundRectComplex;a.dc=a.drawCircle;a.de=a.drawEllipse;a.dp=a.drawPolyStar;a._updateInstructions=function(){this._instructions=this._oldInstructions.slice();this._instructions.push(Graphics.beginCmd);this._fillInstructions&&this._instructions.push.apply(this._instructions,this._fillInstructions);if(this._strokeInstructions){this._instructions.push.apply(this._instructions,this._strokeInstructions);this._strokeStyleInstructions&&this._instructions.push.apply(this._instructions,
this._strokeStyleInstructions)}this._instructions.push.apply(this._instructions,this._activeInstructions);this._fillInstructions&&this._instructions.push(Graphics.fillCmd);this._strokeInstructions&&this._instructions.push(Graphics.strokeCmd)};a._newPath=function(){this._dirty&&this._updateInstructions();this._oldInstructions=this._instructions;this._activeInstructions=[];this._active=this._dirty=false};a._setProp=function(b,d){this[b]=d};a._extendBounds=function(b,d){if(isNaN(this._minX)){this._minX=
this._maxX=b;this._minY=this._maxY=d}else{if(b<this._minX)this._minX=b;else if(b>this._maxX)this._maxX=b;if(d<this._minY)this._minY=d;else if(d>this._maxY)this._maxY=d}};a._updateBounds=function(){for(;boundsQueue.length;)boundsQueue.pop().exec(this)};a._bezierCurveToBounds=function(b,d,e,f,g,h,i,j){this._extendBounds(b,d);this._extendBounds(i,j)};l.Graphics=Graphics})(window);(function(l){DisplayObject=function(){this.initialize()};var c=DisplayObject.prototype;DisplayObject.suppressCrossDomainErrors=false;DisplayObject._hitTestCanvas=document.createElement("canvas");DisplayObject._hitTestCanvas.width=DisplayObject._hitTestCanvas.height=1;DisplayObject._hitTestContext=DisplayObject._hitTestCanvas.getContext("2d");DisplayObject._workingMatrix=new Matrix2D;c.alpha=1;c.cacheCanvas=null;c.id=-1;c.mouseEnabled=true;c.name=null;c.parent=null;c.regX=0;c.regY=0;c.rotation=0;c.scaleX=
1;c.scaleY=1;c.skewX=0;c.skewY=0;c.shadow=null;c.visible=true;c.x=0;c.y=0;c.compositeOperation=null;c.snapToPixel=false;c.onPress=null;c.onClick=null;c.onDoubleClick=null;c.onMouseOver=null;c.onMouseOut=null;c.filters=null;c._cacheOffsetX=0;c._cacheOffsetY=0;c._cacheDraw=false;c._activeContext=null;c._restoreContext=false;c._revertShadow=false;c._revertX=0;c._revertY=0;c._revertAlpha=1;c._minX=NaN;c._minY=NaN;c._maxX=NaN;c._maxY=NaN;c.initialize=function(){this.id=UID.get();this.children=[]};c.isVisible=
function(){return this.visible&&this.alpha>0&&this.scaleX!=0&&this.scaleY!=0};c.draw=function(a,b){if(b||!this.cacheCanvas)return false;a.drawImage(this.cacheCanvas,this._cacheOffsetX,this._cacheOffsetY);return true};c.cache=function(a,b,d,e){var f;if(this.cacheCanvas==null)this.cacheCanvas=document.createElement("canvas");f=this.cacheCanvas.getContext("2d");this.cacheCanvas.width=d;this.cacheCanvas.height=e;f.setTransform(1,0,0,1,-a,-b);f.clearRect(0,0,d+1,e+1);this.draw(f,true);this._cacheOffsetX=
a;this._cacheOffsetY=b;this._applyFilters()};c.updateCache=function(a){if(this.cacheCanvas==null)throw"cache() must be called before updateCache()";var b=this.cacheCanvas.getContext("2d");b.setTransform(1,0,0,1,-this._cacheOffsetX,-this._cacheOffsetY);if(a)b.globalCompositeOperation=a;else b.clearRect(0,0,this.cacheCanvas.width+1,this.cacheCanvas.height+1);this.draw(b,true);if(a)b.globalCompositeOperation="source-over";this._applyFilters()};c.uncache=function(){this.cacheCanvas=null;this._cacheOffsetX=
this._cacheOffsetY=0};c.getStage=function(){for(var a=this;a.parent;)a=a.parent;if(a instanceof Stage)return a;return null};c.localToGlobal=function(a,b){var d=this.getConcatenatedMatrix();if(d==null)return null;d.append(1,0,0,1,a,b);return new Point(d.tx,d.ty)};c.globalToLocal=function(a,b){var d=this.getConcatenatedMatrix();if(d==null)return null;d.invert();d.append(1,0,0,1,a,b);return new Point(d.tx,d.ty)};c.localToLocal=function(a,b,d){a=this.localToGlobal(a,b);return d.globalToLocal(a.x,a.y)};
c.setTransform=function(a,b,d,e,f,g,h,i,j){this.x=a||0;this.y=b||0;this.scaleX=d==null?1:d;this.scaleY=e==null?1:e;this.rotation=f||0;this.skewX=g||0;this.skewY=h||0;this.regX=i||0;this.regY=j||0};c.getConcatenatedMatrix=function(a){if(a)a.identity();else a=new Matrix2D;for(var b=this;b!=null;){a.prependTransform(b.x,b.y,b.scaleX,b.scaleY,b.rotation,b.skewX,b.skewY,b.regX,b.regY);a.prependProperties(b.alpha,b.shadow,b.compositeOperation);b=b.parent}return a};c.hitTest=function(a,b){var d=DisplayObject._hitTestContext,
e=DisplayObject._hitTestCanvas;d.setTransform(1,0,0,1,-a,-b);this.draw(d);d=this._testHit(d);e.width=0;e.width=1;return d};c.getBounds=function(){return this._cacheCanvas?new Rectangle(-this._cacheOffsetX,-this._cacheOffsetY,this.cacheCanvas.width,this.cacheCanvas.height):this._calculateBounds()};c.clone=function(){var a=new DisplayObject;this.cloneProps(a);return a};c.toString=function(){return"[DisplayObject (name="+this.name+")]"};c.cloneProps=function(a){a.alpha=this.alpha;a.name=this.name;a.regX=
this.regX;a.regY=this.regY;a.rotation=this.rotation;a.scaleX=this.scaleX;a.scaleY=this.scaleY;a.shadow=this.shadow;a.skewX=this.skewX;a.skewY=this.skewY;a.visible=this.visible;a.x=this.x;a.y=this.y;a.mouseEnabled=this.mouseEnabled;a.compositeOperation=this.compositeOperation};c.applyShadow=function(a,b){b=b||Shadow.identity;a.shadowColor=b.color;a.shadowOffsetX=b.offsetX;a.shadowOffsetY=b.offsetY;a.shadowBlur=b.blur};c._testHit=function(a){try{var b=a.getImageData(0,0,1,1).data[3]>1}catch(d){if(!DisplayObject.suppressCrossDomainErrors)throw"An error has occured. This is most likely due to security restrictions on reading canvas pixel data with local or cross-domain images.";
}return b};c._applyFilters=function(){if(!(!this.filters||this.filters.length==0||!this.cacheCanvas))for(var a=this.filters.length,b=this.cacheCanvas.getContext("2d"),d=this.cacheCanvas.width,e=this.cacheCanvas.height,f=0;f<a;f++)this.filters[f].applyFilter(b,0,0,d,e)};c._calculateBounds=function(){return new Rectangle(0,0,0,0)};l.DisplayObject=DisplayObject})(window);(function(l){Container=function(){this.initialize()};var c=Container.prototype=new DisplayObject;c.children=null;c.DisplayObject_initialize=c.initialize;c.initialize=function(){this.DisplayObject_initialize();this.children=[]};c.isVisible=function(){return this.visible&&this.alpha>0&&this.children.length&&this.scaleX!=0&&this.scaleY!=0};c.DisplayObject_draw=c.draw;c.draw=function(a,b,d){var e=Stage._snapToPixelEnabled;if(!d){d=new Matrix2D;d.appendProperties(this.alpha,this.shadow,this.compositeOperation)}if(this.DisplayObject_draw(a,
b))return true;b=this.children.length;for(var f=this.children.slice(0),g=0;g<b;g++){var h=f[g];h.tick&&h.tick();if(h.isVisible()){var i=false,j=d.clone();j.appendTransform(h.x,h.y,h.scaleX,h.scaleY,h.rotation,h.skewX,h.skewY,h.regX,h.regY);j.appendProperties(h.alpha,h.shadow,h.compositeOperation);if(!(h instanceof Container)){e&&h.snapToPixel&&j.a==1&&j.b==0&&j.c==0&&j.d==1?a.setTransform(j.a,j.b,j.c,j.d,j.tx+0.5|0,j.ty+0.5|0):a.setTransform(j.a,j.b,j.c,j.d,j.tx,j.ty);a.globalAlpha=j.alpha;a.globalCompositeOperation=
j.compositeOperation||"source-over";if(i=j.shadow)this.applyShadow(a,i)}h.draw(a,false,j);i&&this.applyShadow(a)}}return true};c.addChild=function(a){var b=arguments.length;if(b>1){for(var d=0;d<b;d++)this.addChild(arguments[d]);return arguments[b-1]}a.parent&&a.parent.removeChild(a);a.parent=this;this.children.push(a);return a};c.addChildAt=function(a,b){var d=arguments.length;if(d>2){b=arguments[e-1];for(var e=0;e<d-1;e++)this.addChildAt(arguments[e],b+e);return arguments[d-2]}a.parent&&a.parent.removeChild(a);
a.parent=this;this.children.splice(b,0,a);return a};c.removeChild=function(a){var b=arguments.length;if(b>1){for(var d=true,e=0;e<b;e++)d=d&&this.removeChild(arguments[e]);return d}return this.removeChildAt(this.children.indexOf(a))};c.removeChildAt=function(a){var b=arguments.length;if(b>1){for(var d=[],e=0;e<b;e++)d[e]=arguments[e];d.sort(function(g,h){return h-g});var f=true;for(e=0;e<b;e++)f=f&&this.removeChildAt(d[e]);return f}if(a<0||a>this.children.length-1)return false;b=this.children[a];
if(b!=null)b.parent=null;this.children.splice(a,1);return true};c.removeAllChildren=function(){for(;this.children.length;)this.removeChildAt(0)};c.getChildAt=function(a){return this.children[a]};c.sortChildren=function(a){this.children.sort(a)};c.getChildIndex=function(a){return this.children.indexOf(a)};c.getNumChildren=function(){return this.children.length};c.contains=function(a){for(;a;){if(a==this)return true;a=a.parent}return false};c.hitTest=function(a,b){return this.getObjectUnderPoint(a,
b)!=null};c.getObjectsUnderPoint=function(a,b){var d=[],e=this.localToGlobal(a,b);this._getObjectsUnderPoint(e.x,e.y,d);return d};c.getObjectUnderPoint=function(a,b){var d=this.localToGlobal(a,b);return this._getObjectsUnderPoint(d.x,d.y)};c.clone=function(a){var b=new Container;this.cloneProps(b);if(a)for(var d=b.children=[],e=0,f=this.children.length;e<f;e++)d.push(this.children[e].clone(a));return b};c.toString=function(){return"[Container (name="+this.name+")]"};c._getObjectsUnderPoint=function(a,
b,d,e){var f=DisplayObject._hitTestContext,g=DisplayObject._hitTestCanvas,h=DisplayObject._workingMatrix,i=e&1&&(this.onPress||this.onClick||this.onDoubleClick)||e&2&&(this.onMouseOver||this.onMouseOut);if(this.cacheCanvas){this.getConcatenatedMatrix(h);f.setTransform(h.a,h.b,h.c,h.d,h.tx-a,h.ty-b);f.globalAlpha=h.alpha;this.draw(f);if(this._testHit(f)){g.width=0;g.width=1;if(i)return this}else return null}for(var j=this.children.length-1;j>=0;j--){var k=this.children[j];if(k.isVisible()&&k.mouseEnabled)if(k instanceof
Container)if(i){if(k=k._getObjectsUnderPoint(a,b))return this}else{k=k._getObjectsUnderPoint(a,b,d,e);if(!d&&k)return k}else if(!e||i||e&1&&(k.onPress||k.onClick||k.onDoubleClick)||e&2&&(k.onMouseOver||k.onMouseOut)){k.getConcatenatedMatrix(h);f.setTransform(h.a,h.b,h.c,h.d,h.tx-a,h.ty-b);f.globalAlpha=h.alpha;k.draw(f);if(this._testHit(f)){g.width=0;g.width=1;if(i)return this;else if(d)d.push(k);else return k}}}return null};c._calculateBounds=function(){};l.Container=Container})(window);(function(l){Stage=function(a){this.initialize(a)};var c=Stage.prototype=new Container;Stage._snapToPixelEnabled=false;c.autoClear=true;c.canvas=null;c.mouseX=null;c.mouseY=null;c.onMouseMove=null;c.onMouseUp=null;c.onMouseDown=null;c.snapToPixelEnabled=false;c.mouseInBounds=false;c._tmpCanvas=null;c._activeMouseEvent=null;c._activeMouseTarget=null;c._mouseOverIntervalID=null;c._mouseOverX=0;c._mouseOverY=0;c._mouseOverTarget=null;c.Container_initialize=c.initialize;c.initialize=function(a){this.Container_initialize();
this.canvas=a;this.mouseChildren=true;var b=this;if(l.addEventListener){l.addEventListener("mouseup",function(d){b._handleMouseUp(d)},false);l.addEventListener("mousemove",function(d){b._handleMouseMove(d)},false);l.addEventListener("dblclick",function(d){b._handleDoubleClick(d)},false)}else if(document.addEventListener){document.addEventListener("mouseup",function(d){b._handleMouseUp(d)},false);document.addEventListener("mousemove",function(d){b._handleMouseMove(d)},false);document.addEventListener("dblclick",
function(d){b._handleDoubleClick(d)},false)}a.addEventListener("mousedown",function(d){b._handleMouseDown(d)},false)};c.update=function(){if(this.canvas){this.autoClear&&this.clear();Stage._snapToPixelEnabled=this.snapToPixelEnabled;this.draw(this.canvas.getContext("2d"),false,this.getConcatenatedMatrix(DisplayObject._workingMatrix))}};c.tick=c.update;c.clear=function(){if(this.canvas){var a=this.canvas.getContext("2d");a.setTransform(1,0,0,1,0,0);a.clearRect(0,0,this.canvas.width,this.canvas.height)}};
c.toDataURL=function(a,b){b||(b="image/png");var d=this.canvas.getContext("2d"),e=this.canvas.width,f=this.canvas.height,g;if(a){g=d.getImageData(0,0,e,f);var h=d.globalCompositeOperation;d.globalCompositeOperation="destination-over";d.fillStyle=a;d.fillRect(0,0,e,f)}var i=this.canvas.toDataURL(b);if(a){d.clearRect(0,0,e,f);d.putImageData(g,0,0);d.globalCompositeOperation=h}return i};c.enableMouseOver=function(a){if(this._mouseOverIntervalID){clearInterval(this._mouseOverIntervalID);this._mouseOverIntervalID=
null}if(!(a<=0)){var b=this;this._mouseOverIntervalID=setInterval(function(){b._testMouseOver()},1E3/Math.min(50,a));this._mouseOverX=NaN;this._mouseOverTarget=null}};c.clone=function(){var a=new Stage(null);this.cloneProps(a);return a};c.toString=function(){return"[Stage (name="+this.name+")]"};c._handleMouseMove=function(a){if(this.canvas){if(!a)a=l.event;var b=this.mouseInBounds;this._updateMousePosition(a.pageX,a.pageY);if(b||this.mouseInBounds){b=new MouseEvent("onMouseMove",this.mouseX,this.mouseY);
b.nativeEvent=a;if(this.onMouseMove)this.onMouseMove(b);if(this._activeMouseEvent&&this._activeMouseEvent.onMouseMove)this._activeMouseEvent.onMouseMove(b)}}else this.mouseX=this.mouseY=null};c._updateMousePosition=function(a,b){var d=this.canvas;do{a-=d.offsetLeft;b-=d.offsetTop}while(d=d.offsetParent);if(this.mouseInBounds=a>=0&&b>=0&&a<this.canvas.width&&b<this.canvas.height){this.mouseX=a;this.mouseY=b}};c._handleMouseUp=function(a){var b=new MouseEvent("onMouseUp",this.mouseX,this.mouseY);b.nativeEvent=
a;if(this.onMouseUp)this.onMouseUp(b);if(this._activeMouseEvent&&this._activeMouseEvent.onMouseUp)this._activeMouseEvent.onMouseUp(b);if(this._activeMouseTarget&&this._activeMouseTarget.onClick&&this._getObjectsUnderPoint(this.mouseX,this.mouseY,null,true,this._mouseOverIntervalID?3:1)==this._activeMouseTarget){b=new MouseEvent("onClick",this.mouseX,this.mouseY);b.nativeEvent=a;this._activeMouseTarget.onClick(b)}this._activeMouseEvent=this.activeMouseTarget=null};c._handleMouseDown=function(a){var b;
if(this.onMouseDown){b=new MouseEvent("onMouseDown",this.mouseX,this.mouseY);b.nativeEvent=a;this.onMouseDown(b)}var d=this._getObjectsUnderPoint(this.mouseX,this.mouseY,null,this._mouseOverIntervalID?3:1);if(d){if(d.onPress instanceof Function){b=new MouseEvent("onPress",this.mouseX,this.mouseY);b.nativeEvent=a;d.onPress(b);if(b.onMouseMove||b.onMouseUp)this._activeMouseEvent=b}this._activeMouseTarget=d}};c._testMouseOver=function(){if(!(this.mouseX==this._mouseOverX&&this.mouseY==this._mouseOverY&&
this.mouseInBounds)){var a=null;if(this.mouseInBounds){a=this._getObjectsUnderPoint(this.mouseX,this.mouseY,null,3);this._mouseOverX=this.mouseX;this._mouseOverY=this.mouseY}if(this._mouseOverTarget!=a){if(this._mouseOverTarget&&this._mouseOverTarget.onMouseOut)this._mouseOverTarget.onMouseOut(new MouseEvent("onMouseOver",this.mouseX,this.mouseY));if(a&&a.onMouseOver)a.onMouseOver(new MouseEvent("onMouseOut",this.mouseX,this.mouseY));this._mouseOverTarget=a}}};c._handleDoubleClick=function(a){var b;
if(this.onDoubleClick){b=new MouseEvent("onDoubleClick",this.mouseX,this.mouseY);b.nativeEvent=a;this.onDoubleClick(b)}var d=this._getObjectsUnderPoint(this.mouseX,this.mouseY,null,this._mouseOverIntervalID?3:1);if(d)if(d.onDoubleClick instanceof Function){b=new MouseEvent("onPress",this.mouseX,this.mouseY);b.nativeEvent=a;d.onDoubleClick(b)}};l.Stage=Stage})(window);(function(l){Bitmap=function(a){this.initialize(a)};var c=Bitmap.prototype=new DisplayObject;c.image=null;c.snapToPixel=true;c.DisplayObject_initialize=c.initialize;c.initialize=function(a){this.DisplayObject_initialize();this.image=a};c.isVisible=function(){return this.visible&&this.alpha>0&&this.scaleX!=0&&this.scaleY!=0&&this.image&&(this.image.complete||this.image.getContext)};c.DisplayObject_draw=c.draw;c.draw=function(a,b){if(this.DisplayObject_draw(a,b))return true;a.drawImage(this.image,0,
0);return true};c.clone=function(){var a=new Bitmap(this.image);this.cloneProps(a);return a};c.toString=function(){return"[Bitmap (name="+this.name+")]"};c._calculateBounds=function(){return this.image&&(this.image.complete||this.image.getContext)?new Rectangle(0,0,this.image.width,this.image.height):new Rectangle(0,0,0,0)};l.Bitmap=Bitmap})(window);(function(l){BitmapSequence=function(a){this.initialize(a)};var c=BitmapSequence.prototype=new DisplayObject;c.callback=null;c.currentFrame=-1;c.currentSequence=null;c.currentEndFrame=null;c.currentStartFrame=null;c.nextSequence=null;c.paused=false;c.spriteSheet=null;c.snapToPixel=true;c.DisplayObject_initialize=c.initialize;c.initialize=function(a){this.DisplayObject_initialize();this.spriteSheet=a};c.isVisible=function(){var a=this.spriteSheet?this.spriteSheet.image:null;return this.visible&&this.alpha>
0&&this.scaleX!=0&&this.scaleY!=0&&a&&this.currentFrame>=0&&(a.complete||a.getContext)};c.DisplayObject_draw=c.draw;c.draw=function(a,b){if(this.DisplayObject_draw(a,b))return true;var d=this.spriteSheet.image,e=this.spriteSheet.frameWidth,f=this.spriteSheet.frameHeight,g=d.width/e|0,h=d.height/f|0;if(this.currentEndFrame!=null){if(this.currentFrame>this.currentEndFrame){if(this.nextSequence)this._goto(this.nextSequence);else{this.paused=true;this.currentFrame=this.currentEndFrame}this.callback&&
this.callback(this)}}else{h=this.spriteSheet.totalFrames||g*h;if(this.currentFrame>=h){if(this.spriteSheet.loop)this.currentFrame=0;else{this.currentFrame=h-1;this.paused=true}this.callback&&this.callback(this)}}this.currentFrame>=0&&a.drawImage(d,e*(this.currentFrame%g),f*(this.currentFrame/g|0),e,f,0,0,e,f);return true};c.tick=function(){if(this.currentFrame==-1&&this.spriteSheet.frameData)this.paused=true;this.paused||this.currentFrame++};c.gotoAndPlay=function(a){this.paused=false;this._goto(a)};
c.gotoAndStop=function(a){this.paused=true;this._goto(a)};c.clone=function(){var a=new BitmapSequence(this.spriteSheet);this.cloneProps(a);return a};c.toString=function(){return"[BitmapSequence (name="+this.name+")]"};c.DisplayObject_cloneProps=c.cloneProps;c.cloneProps=function(a){this.DisplayObject_cloneProps(a);a.callback=this.callback;a.currentFrame=this.currentFrame;a.currentStartFrame=this.currentStartFrame;a.currentEndFrame=this.currentEndFrame;a.currentSequence=this.currentSequence;a.nextSequence=
this.nextSequence;a.paused=this.paused;a.frameData=this.frameData};c._goto=function(a){if(isNaN(a))if(a==this.currentSequence)this.currentFrame=this.currentStartFrame;else{var b=this.spriteSheet.frameData[a];if(b instanceof Array){this.currentFrame=this.currentStartFrame=b[0];this.currentSequence=a;this.currentEndFrame=b[1];if(this.currentEndFrame==null)this.currentEndFrame=this.currentStartFrame;if(this.currentEndFrame==null)this.currentEndFrame=this.currentFrame;this.nextSequence=b[2];if(this.nextSequence==
null)this.nextSequence=this.currentSequence;else if(this.nextSequence==false)this.nextSequence=null}else{this.currentSequence=this.nextSequence=null;this.currentEndFrame=this.currentFrame=this.currentStartFrame=b}}else{this.currentSequence=this.nextSequence=this.currentEndFrame=null;this.currentStartFrame=0;this.currentFrame=a}};c._calculateBounds=function(){return this.spriteSheet?new Rectangle(0,0,this.spriteSheet.frameWidth,this.spriteSheet.frameHeight):new Rectangle(0,0,0,0)};l.BitmapSequence=
BitmapSequence})(window);(function(l){Shape=function(a){this.initialize(a)};var c=Shape.prototype=new DisplayObject;c.graphics=null;c.DisplayObject_initialize=c.initialize;c.initialize=function(a){this.DisplayObject_initialize();this.graphics=a?a:new Graphics};c.isVisible=function(){return this.visible&&this.alpha>0&&this.scaleX!=0&&this.scaleY!=0&&this.graphics};c.DisplayObject_draw=c.draw;c.draw=function(a,b){if(this.DisplayObject_draw(a,b))return true;this.graphics.draw(a);return true};c.clone=function(a){a=new Shape(a&&
this.graphics?this.graphics.clone():this.graphics);this.cloneProps(a);return a};c.toString=function(){return"[Shape (name="+this.name+")]"};c._calculateBounds=function(){return this.graphics?this.graphics.getBounds():new Rectangle(0,0,0,0)};l.Shape=Shape})(window);(function(l){Text=function(a,b,d){this.initialize(a,b,d)};var c=Text.prototype=new DisplayObject;Text._workingContext=document.createElement("canvas").getContext("2d");c.text="";c.font=null;c.color=null;c.textAlign=null;c.textBaseline=null;c.maxWidth=null;c.outline=false;c.lineHeight=null;c.lineWidth=null;c.DisplayObject_initialize=c.initialize;c.initialize=function(a,b,d){this.DisplayObject_initialize();this.text=a;this.font=b;this.color=d?d:"#000"};c.isVisible=function(){return Boolean(this.visible&&
this.alpha>0&&this.scaleX!=0&&this.scaleY!=0&&this.text!=null&&this.text!="")};c.DisplayObject_draw=c.draw;c.draw=function(a,b){if(this.DisplayObject_draw(a,b))return true;if(this.outline)a.strokeStyle=this.color;else a.fillStyle=this.color;a.font=this.font;a.textAlign=this.textAlign?this.textAlign:"start";a.textBaseline=this.textBaseline?this.textBaseline:"alphabetic";for(var d=String(this.text).split(/(?:\r\n|\r|\n)/),e=this.lineHeight==null?this.getMeasuredLineHeight():this.lineHeight,f=0,g=0,
h=d.length;g<h;g++){var i=a.measureText(d[g]).width;if(this.lineWidth==null||i<this.lineWidth)this._drawTextLine(a,d[g],f);else{i=d[g].split(/(\s)/);for(var j=i[0],k=1,m=i.length;k<m;k+=2)if(a.measureText(j+i[k]+i[k+1]).width>this.lineWidth){this._drawTextLine(a,j,f);f+=e;j=i[k+1]}else j+=i[k]+i[k+1];this._drawTextLine(a,j,f)}f+=e}return true};c.getMeasuredWidth=function(){return this._getWorkingContext().measureText(this.text).width};c.getMeasuredLineHeight=function(){return this._getWorkingContext().measureText("M").width*
1.2};c.clone=function(){var a=new Text(this.text,this.font,this.color);this.cloneProps(a);return a};c.toString=function(){return"[Text (text="+(this.text.length>20?this.text.substr(0,17)+"...":this.text)+")]"};c.DisplayObject_cloneProps=c.cloneProps;c.cloneProps=function(a){this.DisplayObject_cloneProps(a);a.textAlign=this.textAlign;a.textBaseline=this.textBaseline;a.maxWidth=this.maxWidth;a.outline=this.outline;a.lineHeight=this.lineHeight;a.lineWidth=this.lineWidth};c._getWorkingContext=function(){var a=
Text._workingContext;a.font=this.font;a.textAlign=this.textAlign?this.textAlign:"start";a.textBaseline=this.textBaseline?this.textBaseline:"alphabetic";return a};c._drawTextLine=function(a,b,d){this.outline?a.strokeText(b,0,d,this.maxWidth):a.fillText(b,0,d,this.maxWidth)};c._calculateBounds=function(){};l.Text=Text})(window);(function(l){SpriteSheetUtils=function(){throw"SpriteSheetUtils cannot be instantiated";};SpriteSheetUtils._workingCanvas=document.createElement("canvas");SpriteSheetUtils._workingContext=SpriteSheetUtils._workingCanvas.getContext("2d");SpriteSheetUtils.flip=function(c,a){var b=c.image,d=c.frameData,e=c.frameWidth,f=c.frameHeight,g=b.width/e|0,h=b.height/f|0,i=g*h,j={},k,m;for(m in d){k=d[m];if(k instanceof Array)k=k.slice(0);j[m]=k}var q=[],o=0,n=0;for(m in a){k=a[m];k=d[k[0]];if(k!=null){if(k instanceof
Array){var r=k[0],p=k[1];if(p==null)p=r}else r=p=k;q[n]=m;q[n+1]=r;q[n+2]=p;o+=p-r+1;n+=4}}d=SpriteSheetUtils._workingCanvas;d.width=b.width;d.height=Math.ceil(h+o/g)*f;o=SpriteSheetUtils._workingContext;o.drawImage(b,0,0,g*e,h*f,0,0,g*e,h*f);h=i-1;for(n=0;n<q.length;n+=4){m=q[n];r=q[n+1];p=q[n+2];k=a[m];i=k[1]?-1:1;for(var t=k[2]?-1:1,u=i==-1?e:0,v=t==-1?f:0,s=r;s<=p;s++){h++;o.save();o.translate(h%g*e+u,(h/g|0)*f+v);o.scale(i,t);o.drawImage(b,s%g*e,(s/g|0)*f,e,f,0,0,e,f);o.restore()}j[m]=[h-(p-
r),h,k[3]]}b=new Image;b.src=d.toDataURL("image/png");return new SpriteSheet(b.width>0?b:d,e,f,j)};SpriteSheetUtils.frameDataToString=function(c){var a="",b=0,d=0,e=0,f,g;for(g in c){e++;f=c[g];if(f instanceof Array){var h=f[0],i=f[1];if(i==null)i=h;f=f[2];if(f==null)f=g}else{h=i=f;f=g}a+="\n\t"+g+", start="+h+", end="+i+", next="+f;if(f==false)a+=" (stop)";else if(f==g)a+=" (loop)";if(i>b)b=i;if(h<d)d=h}return e+" sequences, min="+d+", max="+b+a};SpriteSheetUtils.extractFrame=function(c,a){var b=
c.image,d=c.frameWidth,e=c.frameHeight,f=b.width/d|0;if(isNaN(a)){var g=c.frameData[a];a=g instanceof Array?g[0]:g}g=SpriteSheetUtils._workingCanvas;g.width=d;g.height=e;SpriteSheetUtils._workingContext.drawImage(b,a%f*d,(a/f|0)*e,d,e,0,0,d,e);b=new Image;b.src=g.toDataURL("image/png");return b};l.SpriteSheetUtils=SpriteSheetUtils})(window);
